language: go
go:
- 1.13.x
before_install:
- openssl aes-256-cbc -K $encrypted_505bf838ccd2_key -iv $encrypted_505bf838ccd2_iv -in clouds.yaml.enc -out clouds.yaml -d
script:
- make test
after_success:
- bash <(curl -s https://codecov.io/bash)