---
- project:
    merge-mode: squash-merge
    vars:
      functest_project_name: "eu-de_zuul_go"
    check:
      jobs:
        - otc-golangci-lint
        - golang-make-vet
        - goreleaser-build
        - golang-make-functional:
            voting: false
    gate:
      jobs:
        - otc-golangci-lint
        - golang-make-vet
        - goreleaser-build
        - golang-make-functional:
            voting: false
    tag:
      jobs:
        - release-goreleaser
