---
- project:
    merge-mode: squash-merge
    vars:
      functest_project_name: "eu-de_zuul_go"
    check:
      jobs:
        - golangci-lint
        - golang-make-vet
        - goreleaser-build:
            nodeset: fedora-32-large
    gate:
      jobs:
        - golangci-lint
        - golang-make-vet
        - golang-make-functional
        - goreleaser-build:
            nodeset: fedora-32-large
