name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.10

  vet:
    name: vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: make vet

  unit_tests:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: make unit

  acc_tests:
    name: acceptance tests
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    environment: tests
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: make acceptance acceptance-services
        env:
          OS_AUTH_URL: ${{ secrets.AUTH_URL }}
          OS_DOMAIN_NAME: ${{ secrets.USER_DOMAIN_NAME }}
          OS_PASSWORD: ${{ secrets.PASSWORD }}
          OS_USERNAME: ${{ secrets.USERNAME }}
          OS_PROJECT_NAME: ${{ vars.FUNCTEST_PROJECT_NAME }}
          OS_REGION: "eu-de"

  eco_check:
    name: check
    if: >
      always()
    needs: [lint, vet, unit_tests, acc_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # release/v1
        with:
          allowed-skips: acc_tests
          jobs: ${{ toJSON(needs) }}
